# Attack & Defense: collegamenti TCP verso i servizi avversari.
# Richiede il modulo stream. Da includere fuori dal blocco http.

stream {
    # Team 1 -> Document Vault nella VM del Team 2.
    server {
        # Indirizzo contattato dal Team 1 sul Master.
        listen 10.77.1.3:8081;

        # Nginx apre la connessione verso la VM usando questo IP sorgente.
        proxy_bind 10.77.2.1;
        proxy_pass 10.77.2.10:8081;

        # Limiti per apertura della connessione e successiva inattivita'.
        proxy_connect_timeout 3s;
        proxy_timeout 60s;
    }

    # Team 1 -> HelpDesk nella VM del Team 2.
    server {
        listen 10.77.1.3:8082;
        proxy_bind 10.77.2.1;
        proxy_pass 10.77.2.10:8082;
        proxy_connect_timeout 3s;
        proxy_timeout 60s;
    }

    # Team 2 -> Document Vault nella VM del Team 1.
    server {
        listen 10.77.2.3:8081;
        proxy_bind 10.77.1.1;
        proxy_pass 10.77.1.10:8081;
        proxy_connect_timeout 3s;
        proxy_timeout 60s;
    }

    # Team 2 -> HelpDesk nella VM del Team 1.
    server {
        listen 10.77.2.3:8082;
        proxy_bind 10.77.1.1;
        proxy_pass 10.77.1.10:8082;
        proxy_connect_timeout 3s;
        proxy_timeout 60s;
    }
}
